spring:
  application:
    name: sink-csv-app

  cloud:
    stream:
      bindings:
        input:

          group: haliho
          destination: demo-processed
           
server:
  port: 8084

  

  

